### ISSUE TITLE
Listen 80

### ISSUE THREAD

**Issue by stoeffel** [mattheath/puppet-apache#1]
I got the following error, when I started the apache...
Address already in use: make_sock: could not bind to address [::]:80

I think the "Listen 80" in the sites/_site_.conf should be in the httpd.conf and not in the vhost.conf. (this solved the problem for me).

Thanks a lot.

**Comment by mattheath** [comment]
This would usually be the case, but [Boxen](boxen.github.com) installs Nginx by default which listens on port 80, so that port is already in use causing the error above. To get around this, for specific apache testing I configure an Nginx host which proxies onto Apache on a non standard port - eg 14237.

**Comment by stoeffel** [comment]
Okay, but I don't use nginx:-)
